version: "3.3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "1080:1080"
    volumes:
      - .:/var/www/html
    command: dockerup
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: guest
