default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: guest
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
development:
  <<: *default
  database: html_development

test:
  <<: *default
  database: html_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: html_production
  username: html
  password: <%= ENV['HTML_DATABASE_PASSWORD'] %>
